version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    networks:
      - my_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    networks:
      - my_network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    depends_on:
      - postgres
  init:
    build: .
    networks:
      - my_network
    depends_on:
      - pgadmin
  webapp:
    build: ./app
    ports:
      - "25565:8000"
    networks:
      - my_network
    depends_on:
      - pgadmin
      - init

volumes:
  postgres_data:
networks:
  my_network:
